before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -X main.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "yoursurprise/dd-log-proxy:{{ .Version }}-amd64"
      - "yoursurprise/dd-log-proxy:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "yoursurprise/dd-log-proxy:{{ .Version }}-arm64v8"
      - "yoursurprise/dd-log-proxy:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    image_templates:
      - "yoursurprise/dd-log-proxy:{{ .Version }}-armv6"
      - "yoursurprise/dd-log-proxy:latest-armv6"
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    image_templates:
      - "yoursurprise/dd-log-proxy:{{ .Version }}-armv7"
      - "yoursurprise/dd-log-proxy:latest-armv7"
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: yoursurprise/dd-log-proxy:{{ .Version }}
    image_templates:
      - yoursurprise/dd-log-proxy:{{ .Version }}-amd64
      - yoursurprise/dd-log-proxy:{{ .Version }}-arm64v8
      - yoursurprise/dd-log-proxy:{{ .Version }}-armv6
      - yoursurprise/dd-log-proxy:{{ .Version }}-armv7
  - name_template: yoursurprise/dd-log-proxy:latest
    image_templates:
      - yoursurprise/dd-log-proxy:latest-amd64
      - yoursurprise/dd-log-proxy:latest-arm64v8
      - yoursurprise/dd-log-proxy:latest-armv6
      - yoursurprise/dd-log-proxy:latest-armv7