name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: false
  
    - name: Run linting
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m
  
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@v1.0.0
        with:
          go-version: 1.20
          package: ./...
          vulncheck-version: latest
          fail-on-vuln: true
          skip-upload: true
